apiVersion: apps/v1
kind: Deployment
metadata:
  name: catdogs
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: cat-reviews
        image: nginx_cat
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        command: ["/bin/sh"]

      - name: dog-reviews
        image: nginx_dog
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        ports:
        - containerPort: 8080