FROM nginx

RUN apt-get update && apt-get upgrade -y && apt-get install curl

COPY ../htmls/index_dog.html /usr/share/nginx/html/index.html
COPY ../nginx/default_1 /etc/nginx/nginx.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]