FROM nginx

RUN apt-get update && apt-get upgrade -y && apt-get install curl

COPY ../htmls/index_dog.html /usr/share/nginx/html/index.html
COPY ../nginx/default_2 /etc/nginx/nginx.conf
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]